name: Build Forge Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Grant gradlew permissions
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew build

    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: mcdiscordbridge.jar
        path: build/libs/*.jar
